//{"Expect" : "FAIL", "Reason" : "Cotinue outside a loop"}
function main()
{
  continue; 
}
